[details]
meeting_subject = Automation Testing
meeting_link = https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTNhZDE3MzYtOTkwNi00NzBiLThmODMtMGEwNzdmNjNlMWJj%40thread.v2/0?context=%7b%22Tid%22%3a%229bacb18e-078b-40cb-b48d-fd077890bb2c%22%2c%22Oid%22%3a%22b8d14955-134e-463d-bf3f-fb4379195eaa%22%7d

